[package]
name = "stratumx_tooling_l6_0_authority_core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
uuid.workspace = true
editor_dto_law = { path = "../../3.sdk/l5.9-editor-dto-law" }

[lib]
path = "src/tooling_authority_core.rs"
