use crate::{
    AnimationCinematicsAuthoringSuite, AssetGateAndApprovalSurface, AssistantSurface,
    AudioVoiceAuthoringSuite, AutomationAndBatchService, BuildReleaseSurface,
    BuildValidationReleaseSuite, CollaborationSessionSurface, ContentBrowserSystem,
    DestructionFractureAuthoringSuite, DiagnosticsSurface, GraphAuthoringService,
    ImportExportPipelineService, InspectorSystem, InteractionRoutingSystem,
    LearningOnboardingAndHelpSurface, MaterialLookdevAuthoringSuite, OutlinerSystem,
    OverlayAndGizmoSystem, PackageMarketAndDependencyService, PlaytestAndCaptureOperations,
    PluginAndExtensionHost, ProductionDashboardAndTraceability, ProjectBootstrapService,
    QuestEventLogicAuthoringSuite, ReviewAnnotationSurface, SceneEntityAuthoringSuite,
    ScriptAndHotReloadService, SimulationAiAuthoringSuite, TemplatePresetAndScaffoldService,
    TerrainLandscapeAuthoringSuite, ToolContextSystem, UiHudAuthoringSuite, ViewportSystem,
    WeatherEnvironmentAuthoringSuite, WorkspaceLayoutSystem, WorldAuthoringSuite,
};
use stratumx_tooling_l6_0_tool_session::ToolingRuntime;

pub struct EditorProduct {
    pub title: String,
    pub project_name: String,
    pub tooling: ToolingRuntime,
    pub viewport: ViewportSystem,
    pub outliner: OutlinerSystem,
    pub content_browser: ContentBrowserSystem,
    pub inspector: InspectorSystem,
    pub tool_context: ToolContextSystem,
    pub overlay_and_gizmo: OverlayAndGizmoSystem,
    pub workspace_layout: WorkspaceLayoutSystem,
    pub interaction_routing: InteractionRoutingSystem,
    pub assistant_surface: AssistantSurface,
    pub diagnostics_surface: DiagnosticsSurface,
    pub build_release_surface: BuildReleaseSurface,
    pub world_suite: WorldAuthoringSuite,
    pub scene_suite: SceneEntityAuthoringSuite,
    pub terrain_suite: TerrainLandscapeAuthoringSuite,
    pub material_suite: MaterialLookdevAuthoringSuite,
    pub destruction_suite: DestructionFractureAuthoringSuite,
    pub simulation_suite: SimulationAiAuthoringSuite,
    pub weather_suite: WeatherEnvironmentAuthoringSuite,
    pub animation_suite: AnimationCinematicsAuthoringSuite,
    pub audio_suite: AudioVoiceAuthoringSuite,
    pub ui_suite: UiHudAuthoringSuite,
    pub quest_suite: QuestEventLogicAuthoringSuite,
    pub build_suite: BuildValidationReleaseSuite,
    pub project_bootstrap_service: ProjectBootstrapService,
    pub import_export_service: ImportExportPipelineService,
    pub graph_authoring_service: GraphAuthoringService,
    pub automation_service: AutomationAndBatchService,
    pub script_service: ScriptAndHotReloadService,
    pub plugin_host: PluginAndExtensionHost,
    pub template_service: TemplatePresetAndScaffoldService,
    pub package_service: PackageMarketAndDependencyService,
    pub collaboration_surface: CollaborationSessionSurface,
    pub review_surface: ReviewAnnotationSurface,
    pub approval_surface: AssetGateAndApprovalSurface,
    pub playtest_surface: PlaytestAndCaptureOperations,
    pub production_surface: ProductionDashboardAndTraceability,
    pub learning_surface: LearningOnboardingAndHelpSurface,
}

impl Default for EditorProduct {
    fn default() -> Self {
        Self {
            title: String::from("Untitled"),
            project_name: String::from("untitled"),
            tooling: ToolingRuntime::default(),
            viewport: ViewportSystem::default(),
            outliner: OutlinerSystem::default(),
            content_browser: ContentBrowserSystem::default(),
            inspector: InspectorSystem::default(),
            tool_context: ToolContextSystem::default(),
            overlay_and_gizmo: OverlayAndGizmoSystem::default(),
            workspace_layout: WorkspaceLayoutSystem::default(),
            interaction_routing: InteractionRoutingSystem::default(),
            assistant_surface: AssistantSurface::default(),
            diagnostics_surface: DiagnosticsSurface::default(),
            build_release_surface: BuildReleaseSurface::default(),
            world_suite: WorldAuthoringSuite::default(),
            scene_suite: SceneEntityAuthoringSuite::default(),
            terrain_suite: TerrainLandscapeAuthoringSuite::default(),
            material_suite: MaterialLookdevAuthoringSuite::default(),
            destruction_suite: DestructionFractureAuthoringSuite::default(),
            simulation_suite: SimulationAiAuthoringSuite::default(),
            weather_suite: WeatherEnvironmentAuthoringSuite::default(),
            animation_suite: AnimationCinematicsAuthoringSuite::default(),
            audio_suite: AudioVoiceAuthoringSuite::default(),
            ui_suite: UiHudAuthoringSuite::default(),
            quest_suite: QuestEventLogicAuthoringSuite::default(),
            build_suite: BuildValidationReleaseSuite::default(),
            project_bootstrap_service: ProjectBootstrapService::default(),
            import_export_service: ImportExportPipelineService::default(),
            graph_authoring_service: GraphAuthoringService::default(),
            automation_service: AutomationAndBatchService::default(),
            script_service: ScriptAndHotReloadService::default(),
            plugin_host: PluginAndExtensionHost::default(),
            template_service: TemplatePresetAndScaffoldService::default(),
            package_service: PackageMarketAndDependencyService::default(),
            collaboration_surface: CollaborationSessionSurface::default(),
            review_surface: ReviewAnnotationSurface::default(),
            approval_surface: AssetGateAndApprovalSurface::default(),
            playtest_surface: PlaytestAndCaptureOperations::default(),
            production_surface: ProductionDashboardAndTraceability::default(),
            learning_surface: LearningOnboardingAndHelpSurface::default(),
        }
    }
}

impl EditorProduct {
    pub fn refresh_from_tooling(
        &mut self,
    ) -> Result<(), stratumx_tooling_l6_0_tool_session::ToolingError> {
        // Stub implementation - in real code this would sync state from tooling runtime
        Ok(())
    }
}
