use super::models::TestFileInventory;
use super::stats;

pub fn generate_inventory_markdown(inventory: &[TestFileInventory]) -> String {
    let mut md = String::new();
    let giant_files = stats::giant_files(inventory);

    md.push_str("# Quality Contour Inventory\n\n");
    md.push_str("Generated by the inventory system for Phase 3: Quality Contour Surgery.\n\n");
    md.push_str("This document catalogs all test files in 7.quality/suites/ with their sizes, ");
    md.push_str("test families, embedded support code, and domain classifications.\n\n");

    write_giant_files_section(&mut md, &giant_files);
    write_size_categories_section(&mut md, inventory);
    write_giant_families_section(&mut md, &giant_files);
    write_support_section(&mut md, inventory);
    write_suite_breakdown_section(&mut md, inventory);
    write_domain_summary_section(&mut md, inventory);
    write_summary_statistics(&mut md, inventory);

    md
}

fn write_giant_files_section(md: &mut String, giant_files: &[&TestFileInventory]) {
    md.push_str("## 1. Giant Files Requiring Splitting (800+ lines)\n\n");

    if giant_files.is_empty() {
        md.push_str("No giant files found.\n\n");
        return;
    }

    md.push_str(&format!("Found {} giant files:\n\n", giant_files.len()));
    for file in giant_files {
        md.push_str(&format!(
            "- **{}** ({} lines, {} tests)\n",
            file.path.display(),
            file.line_count,
            file.test_count
        ));
        md.push_str(&format!("  - Suite: {}\n", file.suite));
        md.push_str(&format!("  - Domain: {}\n", file.domain.as_str()));
        if !file.families.is_empty() {
            md.push_str("  - Test families:\n");
            for family in &file.families {
                md.push_str(&format!(
                    "    - {} ({} tests, lines {}-{})\n",
                    family.name, family.test_count, family.line_range.0, family.line_range.1
                ));
            }
        }
        md.push('\n');
    }
}

fn write_size_categories_section(md: &mut String, inventory: &[TestFileInventory]) {
    md.push_str("## 2. Files by Size Category\n\n");
    let counts = stats::count_by_size_category(inventory);

    for category in &[
        "Normal (0-300)",
        "Suspicious (301-500)",
        "Requires Split (501-800)",
        "Forbidden (800+)",
    ] {
        md.push_str(&format!(
            "- **{}**: {} files\n",
            category,
            counts.get(*category).copied().unwrap_or(0)
        ));
    }
    md.push('\n');
}

fn write_giant_families_section(md: &mut String, giant_files: &[&TestFileInventory]) {
    md.push_str("## 3. Test Families Within Giant Files\n\n");
    let giant_with_families = stats::giant_family_files(giant_files);

    if giant_with_families.is_empty() {
        md.push_str("No test families identified in giant files.\n\n");
        return;
    }

    for file in giant_with_families {
        md.push_str(&format!("### {}\n\n", file.path.display()));
        for family in &file.families {
            md.push_str(&format!(
                "- **{}**: {} tests (lines {}-{})\n",
                family.name, family.test_count, family.line_range.0, family.line_range.1
            ));
        }
        md.push('\n');
    }
}

fn write_support_section(md: &mut String, inventory: &[TestFileInventory]) {
    md.push_str("## 4. Embedded Support Code Locations\n\n");
    let files_with_support = stats::files_with_support(inventory);

    if files_with_support.is_empty() {
        md.push_str("No embedded support code detected.\n\n");
        return;
    }

    let counts = stats::count_support_by_kind(&files_with_support);
    md.push_str("### Summary by Type\n\n");
    for (kind, count) in counts {
        md.push_str(&format!("- {}: {} instances\n", kind, count));
    }
    md.push('\n');

    md.push_str("### Detailed Locations\n\n");
    for file in files_with_support {
        md.push_str(&format!("#### {}\n\n", file.path.display()));
        for support in stats::support_locations(file) {
            md.push_str(&format!(
                "- {:?}: {} (line {})\n",
                support.kind, support.name, support.line_range.0
            ));
        }
        md.push('\n');
    }
}

fn write_suite_breakdown_section(md: &mut String, inventory: &[TestFileInventory]) {
    md.push_str("## 5. Suite-by-Suite Breakdown\n\n");
    let by_suite = stats::group_by_suite(inventory);
    let mut suites: Vec<_> = by_suite.keys().collect();
    suites.sort();

    for suite in suites {
        let files = &by_suite[suite];
        let total_lines: usize = files.iter().map(|file| file.line_count).sum();
        let total_tests: usize = files.iter().map(|file| file.test_count).sum();
        let avg_lines = if files.is_empty() {
            0
        } else {
            total_lines / files.len()
        };

        md.push_str(&format!("### {}\n\n", suite));
        md.push_str(&format!("- Files: {}\n", files.len()));
        md.push_str(&format!("- Total lines: {}\n", total_lines));
        md.push_str(&format!("- Average lines per file: {}\n", avg_lines));
        md.push_str(&format!("- Total tests: {}\n\n", total_tests));
    }
}

fn write_domain_summary_section(md: &mut String, inventory: &[TestFileInventory]) {
    md.push_str("## 6. Domain Classification Summary\n\n");
    let by_domain = stats::count_by_domain(inventory);

    for domain in &["engine", "sdk", "editor", "tooling", "authoring", "unknown"] {
        let files = by_domain.get(*domain).map(|items| items.len()).unwrap_or(0);
        let tests = by_domain
            .get(*domain)
            .map(|items| items.iter().map(|file| file.test_count).sum())
            .unwrap_or(0);
        md.push_str(&format!(
            "- **{}**: {} files, {} tests\n",
            domain, files, tests
        ));
    }
    md.push('\n');
}

fn write_summary_statistics(md: &mut String, inventory: &[TestFileInventory]) {
    md.push_str("## Summary Statistics\n\n");
    md.push_str(&format!("- Total test files: {}\n", inventory.len()));
    md.push_str(&format!(
        "- Total tests: {}\n",
        stats::total_tests(inventory)
    ));
    md.push_str(&format!(
        "- Total lines: {}\n",
        stats::total_lines(inventory)
    ));
    md.push_str(&format!(
        "- Average lines per file: {}\n",
        stats::average_lines(inventory)
    ));
    md.push_str(&format!(
        "- Giant files (800+): {}\n",
        stats::giant_files(inventory).len()
    ));
    md.push_str(&format!(
        "- Files requiring split (501-800): {}\n",
        inventory
            .iter()
            .filter(|file| matches!(
                file.size_category,
                super::models::SizeCategory::RequiresSplit
            ))
            .count()
    ));
}
